name: kanban_board_app
description: "Kanban Board Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  get: ^4.6.6
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins_w100.ttf
          weight: 100
        - asset: assets/fonts/poppins_w200.ttf
          weight: 200
        - asset: assets/fonts/poppins_w300.ttf
          weight: 300
        - asset: assets/fonts/poppins_w400.ttf
          weight: 400
        - asset: assets/fonts/poppins_w500.ttf
          weight: 500
        - asset: assets/fonts/poppins_w600.ttf
          weight: 600
        - asset: assets/fonts/poppins_w700.ttf
          weight: 700
        - asset: assets/fonts/poppins_w800.ttf
          weight: 800
        - asset: assets/fonts/poppins_w900.ttf
          weight: 900
